services:
  - type: web
    name: bonobo-backend
    runtime: docker
    plan: free
    buildCommand: bun install
    startCommand: bun run start
    envVars:
      - key: PORT
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
    healthCheckPath: /

